// Generated by https://quicktype.io

import { PropertyMapper } from "./TemplateMappings";

export interface PullRequestObject {
	eventKey: string;
	eventKeyMapper: PropertyMapper;
	date: string;
	actor: Actor;
	pullRequest: PullRequest;
}

export interface Actor {
	name: string;
	emailAddress: string;
	id: number;
	displayName: string;
	active: boolean;
	slug: string;
	type: string;
}

export interface PullRequest {
	id: number;
	version: number;
	title: string;
	description: string;
	state: string;
	open: boolean;
	closed: boolean;
	createdDate: number;
	updatedDate: number;
	fromRef: Ref;
	toRef: Ref;
	locked: boolean;
	author: Author;
	reviewers: any[];
	participants: any[];
}

export interface Author {
	user: Actor;
	role: string;
	approved: boolean;
	status: string;
}

export interface Ref {
	id: string;
	displayId: string;
	latestCommit: string;
	repository: Repository;
}

export interface Repository {
	slug: string;
	id: number;
	name: string;
	scmId: string;
	state: string;
	statusMessage: string;
	forkable: boolean;
	project: Project;
	public: boolean;
}

export interface Project {
	key: string;
	id: number;
	name: string;
	description: string;
	public: boolean;
	type: string;
}
