// Generated by https://quicktype.io

export interface PushObject {
	eventKey: string;
	date: string;
	actor: Actor;
	repository: Repository;
	changes: Change[];
}

export interface Actor {
	name: string;
	emailAddress: string;
	id: number;
	displayName: string;
	active: boolean;
	slug: string;
	type: string;
}

export interface Change {
	ref: Ref;
	refId: string;
	fromHash: string;
	toHash: string;
	type: string;
}

export interface Ref {
	id: string;
	displayId: string;
	type: string;
}

export interface Repository {
	slug: string;
	id: number;
	name: string;
	scmId: string;
	state: string;
	statusMessage: string;
	forkable: boolean;
	project: Project;
	public: boolean;
}

export interface Project {
	key: string;
	id: number;
	name: string;
	public: boolean;
	type: string;
}
