// Generated by https://quicktype.io

import { PropertyMapper } from "./TemplateMappings";

export interface Sandbox {
	currentSandbox: string;
	currentSandboxMapper: PropertyMapper;
	standParams: StandParams;
	version: string;
	vms: Vms;
}

export interface StandParams {
	parameters: Parameters;
}

export interface Parameters {
	csi: CSI;
}

export interface CSI {
	csi_schema_username: string;
	csi_schema_password: string;
	csi_exporter_schema_username: string;
	csi_exporter_schema_password: string;
	csi_sender_schema_username: string;
	csi_sender_schema_password: string;
	csi_sync_schema_username: string;
	elastic_schema_prefix: string;
	elastic_schema_suffix: string;
}

export interface Vms {
	vms: { [key: string]: string[] };
}
